version: "3.7"

services:
 server:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: ts-template-node
  volumes:
    - .:/home/node/server
  expose:
    - "3333"
  ports:
    - "3333:3333"
    - "9229:9229"
  command: yarn start
